# Build website
[build]
  command = "yarn run build:prod"
  publish = "dist/"

# Custom 404
[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404

# Terry Pratchett hommage
[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"
